import { put } from '@vercel/blob';
import { getPhotoStyle, CUISINE_PROPS, slugify } from './_lib/photo-style.js';
import { kv } from './_lib/kv.js';
import { verifyToken, getSessionToken } from './_lib/session.js';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Auth guard — protect expensive Gemini API
  try {
    const passwordSet = !!(await kv.get('password'));
    if (passwordSet) {
      const token = getSessionToken(req);
      if (!token || !verifyToken(token)) {
        return res.status(401).json({ error: 'Authentication required' });
      }
    }
  } catch (e) { /* KV unavailable — allow access */ }

  const { title, subjectDescription, cuisine } = req.body;
  if (!title || !subjectDescription) {
    return res.status(400).json({ error: 'title and subjectDescription required' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'GEMINI_API_KEY not configured' });
  }

  // Build the 3-layer prompt
  const props = CUISINE_PROPS[cuisine] || 'clean styling, minimal props, linen napkin';
  const context = `Styled with: ${props}. Single serving, intimate scale.`;
  const style = getPhotoStyle();
  const fullPrompt = `${subjectDescription}\n\n${context}\n\n${style}`;

  try {
    // Call Gemini API
    const geminiResp = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: fullPrompt }] }],
          generationConfig: {
            responseModalities: ['TEXT', 'IMAGE'],
          }
        })
      }
    );

    if (!geminiResp.ok) {
      const err = await geminiResp.text();
      return res.status(500).json({ error: 'Gemini API error', details: err });
    }

    const data = await geminiResp.json();
    const imagePart = data.candidates?.[0]?.content?.parts?.find(p => p.inlineData);

    if (!imagePart) {
      return res.status(500).json({ error: 'No image generated by Gemini' });
    }

    // Upload to Vercel Blob
    const slug = slugify(title);
    const buffer = Buffer.from(imagePart.inlineData.data, 'base64');
    const blob = await put(`photos/${slug}.png`, buffer, {
      access: 'public',
      contentType: 'image/png'
    });

    // Update the recipe photo URL in KV (create entry if not yet in KV)
    try {
      const kvRecipes = await kv.get('recipes') || [];
      const recipe = kvRecipes.find(r => r.slug === slug);
      if (recipe) {
        recipe.photo = blob.url;
      } else {
        kvRecipes.push({ slug, title, photo: blob.url });
      }
      await kv.set('recipes', kvRecipes);
    } catch (e) { /* KV update is best-effort */ }

    return res.json({ url: blob.url, slug });
  } catch (e) {
    return res.status(500).json({ error: 'Photo generation failed', details: e.message });
  }
}
